language: d
sudo: false

d:
 - dmd-2.069.1
 - dmd-2.069.0
 - dmd-2.068.2
 - dmd-2.068.1
 - dmd-2.067.1
 - dmd-2.066.1
 - ldc-0.16.0
 - ldc-0.15.1
 - gdc-4.9.2

addons:
  apt:
    packages:
    - libenet-dev

script:
  - dub test --compiler=${DC} gfm:core
  - dub test --compiler=${DC} gfm:math
  - dub test --compiler=${DC} gfm:net
  - dub test --compiler=${DC} gfm:enet
  - dub test --compiler=${DC} gfm:sdl2
  - dub test --compiler=${DC} gfm:opengl
  - dub test --compiler=${DC} gfm:assimp
  - dub test --compiler=${DC} gfm:freeimage
  - dub test --compiler=${DC} gfm:image
  - dub test --compiler=${DC} gfm:logger
